apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: aiplatform
  region: us-east-1

nodeGroups:
  - name: ng
    desiredCapacity: 4
    instanceType: m5.large
    # availabilityZones: ['us-east-1a', 'us-east-1b', 'us-east-1c', 'us-east-1d']
      # - us-east-1a